### ISSUE TITLE
Translated routes

### ISSUE THREAD

**Issue by arnaudpoullet** [Baptistemontan/leptos_i18n#164] opened 2024-11-09 20:58 UTC
First of all, everything works well so thanks for all your work.

The only thing that bugs me is that there doesn't seem to be a way to have translated paths which I believe is important for SEO and UX (sharing links, bookmarking, etc..)

Currently my only option with the `I18nRoute` is to have

```
/en/search
/fr/search
/nl/search
```

while it would be better to have
```
/en/search
/fr/rechercher
/nl/opzoeken
```

First I tried this
```
<Routes fallback=|| "Page not found.".into_view()>
    <Route path=path!("") view=HomePage/>
    <Route path=path!("/en/search") view=SearchPage/>
    <Route path=path!("/nl/zoeken") view=SearchPage/>
    <Route path=path!("/fr/rechercher") view=SearchPage/>
</Routes>
```
but of course I have no Locale awareness on my page now

Then I tried this
```
<Routes fallback=|| "Page not found.".into_view()>
    <I18nRoute view=|| view! { <Outlet />} >
        <Route path=StaticSegment("") view=HomePage/>
        <Route path=StaticSegment("search") view=SearchPage/>
        <Route path=StaticSegment("zoeken") view=SearchPage/>
        <Route path=StaticSegment("rechercher") view=SearchPage/>
    </I18nRoute>
</Routes>
```
but in this case the Locale is `en` everywhere

I believe having the translations at compile time should allow the generation of translated routes, I wouldn't mind a configuration dedicated to the routes if that's necessary.

I suppose this would make Locale switching more complex because the matching route should be replaced as well but I don't think people switch often. If they do I have to refetch most of the content from my server anyway (be it a blog or an e-commerce). That's the reason why if a user is on `/en/search` and I have a switch button "NL" somewhere, it would actually be a link to navigate to `/nl/opzoeken` which can be done easily with:

```
<A href=move || format!("/{}/{}",Locale:nl.as_str(),td_string!(Locale::nl,common.menu.search_page_path))>{td!(Locale::nl,common.menu.search_page_label)}</A>
```
Which will be quite fast with client-side routing but of course that way of switching is a matter of personal opinion and could be done by re-starting all the resources triggered by the `get_locale()` signal.

Ideally I could do something like this:
```
<Routes fallback=|| "Page not found.".into_view()>
    <I18nRoute view=|| view! { <Outlet />} >
        <Route path=StaticSegment("") view=HomePage/>
        <Route path=translated_path!(common.menu.search_page_path) view=SearchPage/>
    </I18nRoute>
</Routes>
```
but I don't know if that's something that is feasible.

For now the only solution I could come up with is having double path segments for aesthetics only:
```
<Routes fallback=|| "Page not found.".into_view()>
    <I18nRoute view=|| view! { <Outlet />} >
        <Route path=StaticSegment("") view=HomePage/>
        <Route path=path!("/aa/:seo_placeholder) view=SearchPage/>
        <Route path=path!("/ab/:seo_placeholder) view=HowItWorksPage/>
        <Route path=path!("/ac/:seo_placeholder) view=AboutPage/>
    </I18nRoute>
</Routes>
```

Which is less than ideal but with Locale switching on the website only through <A> links as mentionned above it allows me to have:
```
/en/aa/search
/en/ab/how-it-works
/en/ac/about-us

/fr/aa/rechercher
/fr/ab/fonctionnement
/fr/ac/a-propos

/nl/aa/opzoeken
/nl/ab/hoe-het-werkt
/nl/ac/over-ons
```

Do you see any solution to have translated routes ?

**Comment by Baptistemontan** [comment] 2024-11-09 21:16
I'm not currently at home and reading through this on my phone is kind of hard, but I get the idea. I have an idea on how to tackle this problem and will submit it to you when I get home, but I think you will like it!

**Comment by Baptistemontan** [comment] 2024-11-10 00:24
The problem here is that Leptos only gives you two choices: `path!("static_path")` or `path!(":var_path")`, what can be easily implemented is some kind of 
```rust
<Routes fallback=|| "Page not found.".into_view()>
    <I18nRoute view=|| view! { <Outlet />} >
        <Route path=StaticSegment("") view=HomePage/>
        <Route path=I18nPathSegment::new(|locale| td_string(locale, search_path_name)) view=SearchPage/>
    </I18nRoute>
</Routes>
```
it would take as an argument a function that return the path based on the locale.

The other problem is links. You would need to have 
```rust
<A href=move || format!("/{}/{}",Locale:nl.as_str(),td_string!(Locale::nl,common.menu.search_page_path))>{td!(Locale::nl,common.menu.search_page_label)}</A>
```
at every links. This is'nt really nice, I don't really know what to do there, but first issue can be easily implemented

**Comment by arnaudpoullet** [comment] 2024-11-10 15:18
I would love to see the first solution implemented. The only thing I'm wondering is if this would allow multiple segments like `/en/post/:id/comment/:id` or `/fr/publication/:id/commentaire/:id` easily as well.

For the second problem, I don't mind at all if it's less nice and a bit manual, it gives the developer the freedom to do as he whishes and the user clean translated paths.

**Comment by Baptistemontan** [comment] 2024-11-10 18:00
Well I tried, it does work but problems arise when switching locales, if you switch from `/search` to `/fr/search` then the segment is'nt valid anymore, so the whole path as to be updated and not just the locale segment. I don't see any good way to do that. I tried to tap into Leptos inner workings but some stuffs are private... 

To be honest I don't think path names have any impact in term of SEO, or at least it is very very minimal. You can consider that I won't be of any help for this problem, I will still try one or two other things I have in mind but I see this as a lost cause

**Comment by Baptistemontan** [comment] 2024-11-10 18:13
If you want to try here is the code I tried:

```rust
struct I18nSegment<L, F> {
    func: F,
    marker: PhantomData<L>,
}

impl<L, F> Debug for I18nSegment<L, F> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("I18nSegment").finish()
    }
}

impl<L: Locale, F> PossibleRouteMatch for I18nSegment<L, F>
where
    F: Fn(L) -> &'static str,
{
    fn test<'a>(&self, path: &'a str) -> Option<leptos_router::PartialPathMatch<'a>> {
        let locale = leptos::prelude::use_context::<I18nContext<L>>()
            .map(I18nContext::get_locale_untracked)
            .unwrap_or_default();
        let seg = (self.func)(locale);
        StaticSegment(seg).test(path)
    }

    fn generate_path(&self, path: &mut Vec<PathSegment>) {
        ParamSegment("__i18n_segment_placeholder__").generate_path(path);
    }
}

fn make_i18n_segment<L, F>(f: F) -> I18nSegment<L, F>
where
    L: Locale,
    F: Fn(L) -> &'static str + 'static + Send + Sync,
{
    I18nSegment {
        func: f,
        marker: PhantomData,
    }
}

macro_rules! i18n_path {
    ($t:ty, $func:expr) => {
        { make_i18n_segment<$t, _>(move |__locale: $t| $func(__locale)) }
    };
}
```

**Comment by arnaudpoullet** [comment] 2024-11-10 18:15
Too bad it is not as easy as one would hope. Would having a different behaviour like always redirecting from `/` to the default locale `/fr` for example and this way always have a Locale segment help ? That would make `/search` impossible. I don't know if having routes without a Locale segment for the default language is important for you. I find it more consistent to always have one, but then I don't know if that would help in this case.

Not sure the impact is huge for SEO indeed but seeing and sharing a translated route makes for a better browsing experience I believe.

**Comment by arnaudpoullet** [comment] 2024-11-10 18:17
Thank you for the code excerpt! I'll check it out.

**Comment by Baptistemontan** [comment] 2024-11-10 21:05
I don't know how the fuck did I pulled it off, but it works. Like, way better than I thought, you don't even have to format the links, it just works. Try the branch of #165 and tell me if it works like you want

**Comment by Baptistemontan** [comment] 2024-11-10 21:06
The only thing you have to do is ```rust
use leptos_i18n::i18n_path;

<Route path=i18n_path!(Locale, |locale| td_string(locale, path_name)) view=.. />
```

**Comment by Baptistemontan** [comment] 2024-11-10 21:09
There is still some bugs, I'll try to fix them

**Comment by arnaudpoullet** [comment] 2024-11-10 22:39
Nice !

With your last commit navigating from one page to another in a specific Locale works well even though url and label show another language. It basically doesn't care about the url or the locale segment, but knows which page to bring me to, so it's a bit like magic ?

If I start with `/fr/rechercher` it gets the translations right except for this in my menu:
`<A href=move || format!("/{}/{}",locale(),t_string!(i18n,common.menu.search_path))  {..} class="font-semibold text-gray-900 hover:bg-gray-50">{t!(i18n,common.menu.search_label)}</A>`
which has `Submit` (en) label and path `/en/submit` for another link

When loading from a fresh url in the URL bar it does respect the locale segment. But due to my first obervation switching from one language to another with a link doesn't work. I have yet to try switching the locale programmatically, if that works it's even easier.

**Comment by Baptistemontan** [comment] 2024-11-10 22:55
Sorry but it's the fifth time I read your comment and I don't understand a thing, what are the steps you do, whatdo you see and what should be the expected result ?

**Comment by arnaudpoullet** [comment] 2024-11-10 23:05
Yeah, I'll create minimum reproducible example, just a minute

**Comment by Baptistemontan** [comment] 2024-11-10 23:06
Thanks !

**Comment by arnaudpoullet** [comment] 2024-11-11 01:00
Well... this did not go well. I'm not able to compile my MRE with `cargo leptos watch`, there seems to be a memory leak when building the server binary. I tried on `1.84-nightly` and `1.82-stable`. Using `0.5.0-rc1` instead of the last commit from the `i18n_path` branch does not help but removing the `leptos_i18n` dependency completely does.

I must have done some config wrong. Here is the repo if you want to take a look: [i18n_leptos_translated_routes_mre](https://github.com/arnaudpoullet/i18n_leptos_translated_routes_mre)
I'm going to sleep on it in the meantime and try again tomorrow.

**Comment by arnaudpoullet** [comment] 2024-11-11 13:20
So I was able to compile my MRE by commenting some `<A></A>` links with `leptos_i18n` macros in it. It still needed around 70gb of RAM/Swap space to build. I pushed those changes but I'm not sure you'll be able to compile.

There is clearly some memory leak in the way I'm using the library which I think is a bug.

Basically there are 2 issues:
- Text outside of a route context is not translated eventhough it's all within the `I18nContextProvider` e.g. menu links
```
<Router>
 menu links //not translated
  <Routes>
    <Route> view </Route> //translated
  </Routes>
</Router>
```
- Navigating with an `A` link (even within a route context) to another locale does not work

    on page `/nl` clicking on `<A href="/en">en</A>` redirects it immediately to `/nl`

**Comment by Baptistemontan** [comment] 2024-11-11 16:54
Ok the fix was very easy, things should work as expected and no need for an `on:click` listener

**Comment by Baptistemontan** [comment] 2024-11-11 18:59
The changed Iade to the router to fix that fucked up the history, just pushed a fix

**Comment by arnaudpoullet** [comment] 2024-11-12 03:32
Thanks a lot for the fixes, it's impressive how the client-side routing works perfectly.

Refreshing works now too with the history fixed.

There are still a couple of things that do not have the expected bahaviour with the latest version.

- When I enter `/` in the navigation bar I'm directly redirected to `/en` while my default language is `fr`. I suppose there should not be any redirection, but if there is one, it should be `/fr`.
- When I enter `/fr` in the navigation bar, the menu elements only (which are outside of the route context) are in english instead of french

On my end I still have to fix the build issues, that seems to be due to my setup.

**Comment by Baptistemontan** [comment] 2024-11-12 03:37
Weird, I did not get those behavior on any of the tests projects I made nor on the repo you sent me

**Comment by arnaudpoullet** [comment] 2024-11-12 14:15
I think you're right. I was probably not including your latest commits. I'm able to build with [fixed history 6f97224](https://github.com/Baptistemontan/leptos_i18n/pull/165/commits/6f9722401778335e1f7965a6fe85a868b633f076) but not with the next commit [router refactor de2a7ca](https://github.com/Baptistemontan/leptos_i18n/pull/165/commits/de2a7caa9f38bdcc88b6f36cbc584e8bbca556fc) and the nest 2 commits on stable 1.82. I have following compile errors [rev-de2a7ca-compile-errors.txt](https://github.com/user-attachments/files/17717717/rev-de2a7ca-compile-errors.txt).
What rust version are you using? If it's only me, I won't be able to give any feedback until I get my setup in order so please bear with me. I would be very surprised that the same code with the same version of rust does not give the same result. I did a `cargo clean' and removed the Cargo.lock to start from scratch, but nothing gives.

Anyway, if everything is fine on your side, thank you for making this feature work. I have been looking for a while for a way to get localized routes and this crate together with Leptos makes it simple to do.

**Comment by Baptistemontan** [comment] 2024-11-12 14:41
Not at home right now, but I'm pretty sure I'm using the latest nightly compiler

**Comment by arnaudpoullet** [comment] 2024-11-12 14:51
Alright, thank you, I'm curious to see. I just tried with the 1.84-nightly version from 11/11/2024 and it gives me the same errors unfortunately.

**Comment by arnaudpoullet** [comment] 2024-11-12 17:16
Being on Ubuntu I tried the latest commit on another computer that has Windows with 1.82 stable and it shows the same errors on `cargo check`

**Comment by Baptistemontan** [comment] 2024-11-12 17:16
Well I forgot to implement Clone for the i18n segment, it should compile now

**Comment by Baptistemontan** [comment] 2024-11-12 17:18
No idea how it passed CI tho

**Comment by arnaudpoullet** [comment] 2024-11-12 18:07
Nice, the build works correctly on Windows now. But the 2 issues I mentioned earlier still stand. 

Do you know why entering on `/` redirects to `/en` when my default language is french ?

When entering the site on `/fr`, do you have any idea why the menu elements are not translated?

**Comment by Baptistemontan** [comment] 2024-11-12 18:11
> Do you know why entering on `/` redirects to `/en` when my default language is french ?

What's your Accept-Language header ? If english is first, then it is normal to get redirected from `/` to `/en`, *explicit* segments have priority, if no segment then it tries to find a fallback. If you have a cookie for "fr" then accessing "/" will leave you at "/" and not redirect

**Comment by arnaudpoullet** [comment] 2024-11-12 18:17
Alright, yes, that totally makes sense then. Thanks for the explanation!

**Comment by Baptistemontan** [comment] 2024-11-12 18:21
Ok I see the problem yes, On page request the menu take the defaulted locale. The reason for this is because the router run *after* the menu is rendered. So the update of the locale based on the URL happens after the menu is rendered. Basically the context is created, it found that your Accept-Language header is english, it renders in english, then the router see the URL and update the context, and the inner route is rendered with the correct locale

**Comment by Baptistemontan** [comment] 2024-11-12 18:24
So the question is how do you fix this? Either you make your menu render inside the router, or I need to update the context creation to take into account that case

**Comment by Baptistemontan** [comment] 2024-11-12 18:26
The problem is, the context is created *before* the main router, so there is no router context, it is not possible to access use_location

**Comment by Baptistemontan** [comment] 2024-11-12 18:28
I'll try to come up with a solution, but in the mean time just render your menu inside the router and things should work

**Comment by arnaudpoullet** [comment] 2024-11-12 20:58
By moving the menu to a component and calling it on every page, it does indeed work as expected.

This should probably be documented, but for me, that is all I wanted, so thanks a lot.

I'll be testing it with additional segments in the future

**Comment by Baptistemontan** [comment] 2024-11-12 21:00
You don't have to call it every page, you can put it above the Outlet in the view you pass to the router

**Comment by arnaudpoullet** [comment] 2024-11-12 21:16
True, works just as well. Awesome !

**Comment by arnaudpoullet** [comment] 2024-11-13 15:31
Som final words for prosperity:
By moving the the header to the view I can build on my Ubuntu without issues again after resolving following error:
```
   Compiling server v0.1.0 (/home/arnaud/perso/i18n_leptos_mre/server)
error: queries overflow the depth limit!
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`server`)
  = note: query depth increased by 130 when computing layout of `{async block@<leptos::into_view::View<tachys::html::element::HtmlElement<tachys::html::element::elements::Main, (tachys::html::class::Class<tachys::view::static_types::Static<"mt-20">>,), ((leptos::into_view::View<tachys::html::element::HtmlElement<tachys::html::element::elements::Header, (tachys::html::class::Class<tachys::view::static_types::Static<"absolute inset-x-0 top-0 z-50 pt-2">>,), ((tachys::html::element::HtmlElement<tachys::html::element::elements::Nav
```

Moving it back out, shows this error anyway: 
```
thread 'main' panicked at /home/arnaud/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.7.0-rc1/src/link.rs:142:16:
called use_resolved_path outside a <Router>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Which is a good thing.

I'll update my repo if the linked PR is ever merged

**Comment by Baptistemontan** [comment] 2024-11-13 18:36
You still have an error when building ?

**Comment by arnaudpoullet** [comment] 2024-11-13 19:07
Everything works perfectly now.

**Closed** 2024-11-18 00:50 UTC
