### ISSUE TITLE
Locales Cache (?) not updating

### ISSUE THREAD

**Issue by ogcatt** [Baptistemontan/leptos_i18n#86] opened 2023-12-24 02:01 UTC
I am using actix and translations work fine for locales at first glance (in this example I am using EN & FR). However, when I update the values in the json files, the site does not update from the previous translations, even after rebuilding the project (or doing CTRL+Shift+R). The only way the translations update is if I change the key name in the json and within the rust implementation itself.

I have no idea why or how this is happening.

Any help would be appreciated.

I can provide any code that is needed.

**Comment by ogcatt** [comment] 2023-12-24 02:12
For reference, I am running `cargo leptos watch` for running the dev instance of my site

**Comment by Baptistemontan** [comment] 2023-12-24 07:28
Yes it's an issue I ran into too, I think the compiler make the assumption that all macros are code to code, and are pure, so that it can cache a lot of things and not reexpand every macro at every rebuild. So the load_locales macro is not rerunned when the watcher update if no code has been changed. The trigger is not to change the keys in the json, the trigger is that you changed code, whatever code. I know it's frustrating but forcing a full macros reload at every rebuild would be a huge pain, and there is no way for now to specify specific macros as impure or something like this.

**Comment by ogcatt** [comment] 2023-12-24 16:37
How can I do a full macro reload?

**Comment by Baptistemontan** [comment] 2023-12-26 21:21
No idea, I don't know the internals of leptos watch so I can't give you any tips on that...

**Comment by Baptistemontan** [comment] 2024-01-31 11:13
I've stumbled across the [path tracking api](https://github.com/rust-lang/rust/issues/99515) and implemented it with #93, it needs nightly but would solve the problem. I'll push `v0.3.0-rc.1` pretty soon with those chnages, so if you could try it and give a feedback I would greatly appreciate it.

**Comment by Baptistemontan** [comment] 2024-07-27 03:34
I'm pretty sure #93 fixed up the issue as much as possible, there is'nt more I can do from this side, the rest of the problem is from the compiler itself, so I'm closing this issue

**Closed by Baptistemontan** 2024-07-27 03:34 UTC
